upstream websocket {
    ip_hash;
    server wsserver1:8080;
    server wsserver2:8080;
    server wsserver3:8080;
}

server {
    listen 80;

    location /ws {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }

    location /health {
        proxy_pass http://websocket;
    }
}
